pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["additionaliks.htm","Bedienung &#62; Stammdaten &#62; Weitere IKs","Bedienung Stammdaten Müssen Sie Daten für mehrere Krankenhäuser einliefern? Hinterlegen Sie hier die zusätzlichen IKs und Sie können diese im Drop...",""],
["aenderungshistorie.htm","Anhang &#62; Änderungshistorie","Anhang Änderungshistorie Navigation: Anhang Änderungshistorie Im folgenden finden Sie die Änderungen am InEK Datenportal seit November 2012 in umg...",""],
["basehandling.htm","Bedienung &#62; Allgemeine Bedienung","Bedienung Allgemeine Bedienung Navigation: Bedienung Allgemeine Bedienung Einteilung der Dialoge Die Dialogseiten des InEK Datenportals bestehen i...",""],
["changepassword.htm","Bedienung &#62; Stammdaten &#62; Kennwort ändern","Bedienung Stammdaten Kennwort ändern Navigation: Bedienung Stammdaten Kennwort ändern Möchten Sie Ihr Kennwort ändern? Geben Sie dazu Ihr bisherig...",""],
["codes.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Kodes","Bedienung PEPP-Vorschlagsverfahren Kodes Navigation: Bedienung PEPP-Vorschlagsverfahren Kodes Bei einem Vorschlag zur Weiterentwicklung Leistungsb...",""],
["cooperation.htm","Bedienung &#62; Kooperation","Bedienung Kooperation Navigation: Bedienung Kooperation Das InEK Datenportal wurde entwickelt, damit Die auf komfortable Art und Weise Ihre Daten,...",""],
["datavisibility.htm","Bedienung &#62; Sichtbarkeit der Daten","Bedienung Sichtbarkeit der Daten Navigation: Bedienung Sichtbarkeit der Daten Sämtliche Daten, die Sie erfassen, sind an Ihr Benutzerkonto gebunde...",""],
["documents.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Dokumente","Bedienung PEPP-Vorschlagsverfahren Dokumente Navigation: Bedienung PEPP-Vorschlagsverfahren Dokumente In dieser Registerkarte haben Sie die Möglic...",""],
["dropbox.htm","Bedienung &#62; DropBox","Bedienung DropBox Navigation: Bedienung DropBox Haben Sie größere Datenmengen, die Sie im Rahmen der Datenlieferung gem. 21 KHEntgG oder aus sonst...",""],
["dropboxcreate.htm","Bedienung &#62; DropBox &#62; DropBox anlegen","Bedienung DropBox DropBox anlegen Navigation: Bedienung DropBox DropBox anlegen Nach Klick auf [ DropBox anlegen ] erhalten Sie diesen Dialog: Abb...",""],
["dropboxfill.htm","Bedienung &#62; DropBox &#62; DropBox befüllen","Bedienung DropBox DropBox befüllen Navigation: Bedienung DropBox DropBox befüllen Wählen Sie aus der Liste der offenen DropBoxen (siehe oben) die ...",""],
["editusermaintenance.htm","Bedienung &#62; Stammdaten &#62; Stammdaten editieren","Bedienung Stammdaten Stammdaten editieren Navigation: Bedienung Stammdaten Stammdaten editieren Die Stammdaten entsprechen im Wesentlichen den Dat...",""],
["enhancement.htm","Einführung &#62; Weiterentwicklung / Anfragen","Einführung Weiterentwicklung / Anfragen Navigation: Einführung Weiterentwicklung / Anfragen Das InEK Datenportal ermöglicht Ihnen die Übermittlung...",""],
["features.htm","Funktionen","Funktionen Navigation: No topics above this level Funktionen Das InEK Datenportal ist dafür ausgelegt, Ihnen künftig eine Vielzahl an Funktionen z...",""],
["help.htm","Bedienung &#62; Hilfe","Bedienung Hilfe Navigation: Bedienung Hilfe Die Dialogführung ist so gestaltet, dass diese weitgehend intuitiv bedient werden kann. Dennoch, was e...",""],
["introduction.htm","Einführung","Einführung Navigation: No topics above this level Einführung Das InEK Datenportal wurde entwickelt, um Ihnen auf komfortable Art und Weise die Ein...",""],
["konfiguration.htm","Bedienung &#62; Stammdaten &#62; Konfiguration","Bedienung Stammdaten Konfiguration Navigation: Bedienung Stammdaten Konfiguration Auf dieser Seite des InEK Datenportal können Sie Ihren Account k...",""],
["login.htm","Bedienung &#62; Login","Bedienung Login Navigation: Bedienung Login Startpunkt des InEK Datenportal ist der Login-Dialog. Die zu übermittelnden Daten dienen insbesondere ...",""],
["maintenancefeatures.htm","Bedienung &#62; Stammdaten &#62; Funktionen","Bedienung Stammdaten Funktionen Navigation: Bedienung Stammdaten Funktionen Das InEK Datenportal ist dafür ausgelegt, Ihnen künftig eine Vielzahl ...",""],
["notes.htm","Einführung &#62; Hinweise","Einführung Hinweise Navigation: Einführung Hinweise Dieses Handbuch enthält diverse Abbildungen des Programms (Screenshots). Das Aussehen der Dial...",""],
["nub.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB)","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Gemäß 6 Abs. 2...",""],
["nubaddcosts.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Mehrkosten","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Mehrkosten Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Meh...",""],
["nubdescription.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Beschreibung","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Beschreibung Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) B...",""],
["nubdetails.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Methodendetails","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Methodendetails Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB...",""],
["nubkeyfigures.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Kennzahlen","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Kennzahlen Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Ken...",""],
["nublist.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Auflistung NUB-Anfragen","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Auflistung NUB-Anfragen Navigation: Bedienung Neue Untersuchungs- und Behandlungsmetho...",""],
["nubuserinformation.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Stammformblatt","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Stammformblatt Navigation: Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB)...",""],
["overview.htm","Bedienung &#62; Übersicht","Bedienung Übersicht Navigation: Bedienung Übersicht Die Übersicht ist die \"Schaltzentrale\" Ihres Portals. Hier werden die von Ihnen gewählten Funk...",""],
["overviewfeatures.htm","Einführung &#62; Funktionsüberblick","Einführung Funktionsüberblick Navigation: Einführung Funktionsüberblick Das InEK Datenportal bietet Ihnen derzeit diese Funktionen: DropBox Sie kö...",""],
["pepp-propblem.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Problemstellung, Lösungsvorschlag","Bedienung PEPP-Vorschlagsverfahren Problemstellung, Lösungsvorschlag Navigation: Bedienung PEPP-Vorschlagsverfahren Problemstellung, Lösungsvorsch...",""],
["peppproposal.htm","Bedienung &#62; PEPP-Vorschlagsverfahren","Bedienung PEPP-Vorschlagsverfahren Navigation: Bedienung PEPP-Vorschlagsverfahren Das PEPP-Vorschlagsverfahren dient dazu, externen Sachverstand i...",""],
["preconditions.htm","Einführung &#62; Systemvoraussetzung","Einführung Systemvoraussetzung Navigation: Einführung Systemvoraussetzung Beim InEK Datenportal handelt es sich um eine Applikation, die auf einem...",""],
["register.htm","Bedienung &#62; Registrierung","Bedienung Registrierung Navigation: Bedienung Registrierung Um den Service nutzen zu können, ist eine vorherige Registrierung erforderlich. Klicke...",""],
["requestpassword.htm","Bedienung &#62; Kennwort anfordern","Bedienung Kennwort anfordern Navigation: Bedienung Kennwort anfordern Sollten Sie als registrierter Anwender einmal Ihr Kennwort vergessen haben, ...",""],
["search.htm","Bedienung &#62; Suche","Bedienung Suche Navigation: Bedienung Suche In diversen Formularen, z.B. beim PEPP-Vorschlagsverfahren, wird die Eingabe von Kodes benötigt. Das I...",""],
["templates.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Vorlagen","Bedienung Neue Untersuchungs- und Behandlungsmethoden (NUB) Sie können aus Ihren NUB-Anfragen Vorlagen erstellen und diese zu einem späteren Zeitp...",""],
["termsofuse.htm","Einführung &#62; Nutzungsbedingungen","Einführung Nutzungsbedingungen Navigation: Einführung Nutzungsbedingungen Das InEK stellt das InEK Datenportal für interessierte Nutzer kostenlos ...",""],
["testedbrowsers.htm","Anhang &#62; Getestete Browser","Anhang Getestete Browser Navigation: Anhang Getestete Browser Das InEK Datenportal wurde und wird vom InEK mit diversen Browsern auf den InEK-Syst...",""],
["usage.htm","Bedienung","Bedienung Navigation: No topics above this level Bedienung Die Bedienung des InEK Datenportals wurde so gestaltet, dass sie weitgehend intuitiv od...",""],
["userinformation.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Stammformblatt","Bedienung PEPP-Vorschlagsverfahren Damit das InEK Sie über den Status Ihres Vorschlags informieren kann, ist die Angabe Ihrer Adresse erforderlich...",""],
["usermaintenance.htm","Bedienung &#62; Stammdaten","Bedienung Stammdaten Navigation: Bedienung Stammdaten Die Stammdaten dienen der Speicherung von Informationen zu Ihrem Benutzerkonto und Ihrem Kra...",""],
["usermaintenanceother.htm","Bedienung &#62; Stammdaten &#62; Sonstiges","Bedienung Stammdaten Sonstiges Navigation: Bedienung Stammdaten Sonstiges Im Bereich Sonstiges steht Ihnen eine Funktion zum Ändern Ihres Kennwort...",""],
["webrequest_content.htm","InEK Datenportal","Einführung Nutzungsbedingungen Systemvoraussetzung Hinweise Bedienung Allgemeine Bedienung Login Registrierung Kennwort anfordern Übersicht Suche ...",""],
["webrequest_ftsearch.htm","InEK Datenportal","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""],
["webrequest_kwindex.htm","InEK Datenportal","- B - Bedienung Betriebssystem - D - Datenlieferung Datenportal Dialogbedienung Dokumente DropBox - E - Einführung - G - Gewährleistung - H - Haft...",""]];
