= Use Cases

Im Folgenden sind eingie ausgewählte Use Cases detaillierter beschrieben.

[options="header",cols="a"]
|==================================
| *Use Case: Registrierung* 
| *System* +
{nbsp}{nbsp}
InEK Datenportal

| *Ebene* +
{nbsp}{nbsp}
Anwenderziel 

| *Primärakteur*
| *Stakeholder und Interessen*
| *Vorbedingungen*
| *Nachbedingungen*
| *Standardablauf*

. Anwender füllt das Registrierungsformular (mit Anwendernamen, Email-Adresse, Kennwort etc.) aus und gibt an, welche Dienste er (sie) nutzen möchte
. Anwender drückt Registrierungs-Knopf
. System prüft die Daten
. System speichert die Daten und sendet dem Anwender einen Aktivierungslink
. Anwender folgt dem Link und meldet sich mittels Kennwort an
. System aktiviert das Konto 
. Soweit freizuschaltende Dienste angefordert wurden, sendet System eine Mail mit Freischalt- und Sperrlink an InEK-Mitarbeiter
. InEK-Mitarbeiter prüft die Daten und löst über einen der Links eine entsprechende Aktion aus
. Anwender erhält eine Benachrichtigung über Freischaltung oder Sperrung

| *Erweiterungen / alternative Abläufe*

{nbsp}{nbsp}1.a Anwender bricht die Eingabe ab: Die Daten werden verworfen. +
{nbsp}{nbsp}3.a System stellt Eingabefehler fest: Anzeige derselben und weiter mit 1. +
{nbsp}{nbsp}3.b System stellt bekannte Daten fest: Anzeige eines Hinweises (z.B. „Anwendername bereits vergeben“, „Email bereits genutzt, haben Sie Ihr Kennwort vergessen?“, …) und weiter mit 1. +
{nbsp}{nbsp}5.a Anwender aktiviert nicht innerhalb einer festzulegenden Aktivierungsgrenze (z. B. 3 Tage): Verwerfen der Registrierungsdaten +
{nbsp}{nbsp}5.b Anwender registriert nach Ablauf der Aktivierungsgrenze: Hinweis auf abgelaufene Daten und Auffor-derung den Registrierungsprozess erneut zu durchlaufen +
{nbsp}{nbsp}8.a InEK-Mitarbeiter reagiert nicht innerhalb einer festgelegten Zeitspanne: Erinnerungsmail, eventuell an größeren Adressatenkreis 

| *Spezielle Anforderungen*

| *Technik- und Datenvariationen*
| *Häufigkeit des Auftretens* +
{nbsp}{nbsp}Einmal je Anwender. Ca. 2000 bis 5000 Anwender
| *Offene Fragen*

|==================================



link:DataPortal.md#UseCases[Zurück zum Hauptdokument]
