== Account Service

Dient dazu, Benutzer unabhängig von dem jeweiligen Portal zu verwalten.
Dazu gehören neben den persönlichen Daten auch das Passwort und die Rechte.

- Anlegen Benutzerkonto
- Rechteverwaltung (kooperativ, IK-Admin)
- Anmeldung (interaktiv)
- Anmeldung (Mitnahme von anderem Portal, SSO)

nicht dazu gehören
- Portalspezifische Anwenderdaten
- Daten, die über die reinen Anwenderdaten hinausgehen wie beispw. Dokumente
- Konfiguration von Verhalten (beispw. Speicherdaer von Dropbox)

Daten, die zum Anwenderkonto gehören

- Username
- E-Mail
- Passwordhash (+ salt)
- Vorname, Nachname
- Rolle
- Firma/Krankenhaus
- Adresse
- Kontaktdaten
- Liste der IKs
- Liste der Kooperationen
- Liste der Features
- Liste der vom IK-Admin hinterlegten Rechte

Testen des Services
- Unit Test interner Funktionen, die über einfache Zugriffe hinausgehen
- Integrationstest via Projekt, dass die Schnittstellen anspricht

API

Account
- RegisterAccount(account) : void 
- Activate Account(username/email, password, activationKey) : account
- SaveAccount(account) : account
- Login (username/email, password) : account
- GetTransferToken (secret) : token
- LoginByToken (token) : account
- ChangePassword(secret, oldPassword, newPassword)
- RequestPassword(username/email, password) : void
- ConfirmPassword(username/email, password, activationKey) : void
- RequestNewEmail(username, newEmail) : void
- ConfirmNewEmail(activationKey) : void

Cooperation
SaveCooperation()

IkAdmin

AccessRights
GetAccessRight(Secret, Feature, IK)
GetAccessRight(Secret, Feature, IK, PartnerAccountId)

"account" ist in diesem Zusammenhang ein DTO, das mittels JSON übertragen wird.
Neben den in der Account-Klasse des AccountServices vorhandenen Properties enthält dieses DTO ein Secret (z.B. UUID), 
welches zur Anforderung eines Tokens für die Anmeldung bei einem anderen Portal genutzt werden kann. 
Dieses Secret wird jeweils bei Übermittlung des Accounts zum aufrufenden Programm erzeugt. 
Es wird ungültig bei Anforderung eines TransferTokens respektive nach Ablauf eines Gültigkeitzeitraums, jenachdem, welches Ereignis zuerst eintritt.
Dabei ist zu beachten, dass der Anwender sich gleichzeitig mit mehreren Browswern anmelden könnte; hier muss der AccountService alle Secrets kennen.
Sollten mehrerer AccountServivces eingesetzt werden, müssen alle über das Wissen um gültige Secrets verfügen.
Die Secrets werden daher temporär in einer Datenbank (SQL oder Key-Value-Store) hinterlegt.
