pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["additionaliks.htm","Bedienung &#62; Stammdaten &#62; Weitere IKs","Bedienung Stammdaten Weitere IKs Navigation: Bedienung Stammdaten Weitere IKs Müssen Sie Daten für mehrere Krankenhäuser einliefern? Hinterlegen S...",""],
["basehandling.htm","Bedienung &#62; Allgemeine Bedienung","Bedienung Allgemeine Bedienung Navigation: Bedienung Allgemeine Bedienung Einteilung der Dialoge Die Dialogseiten des InEK Datenportals bestehen i...",""],
["changepassword.htm","Bedienung &#62; Stammdaten &#62; Kennwort ändern","Bedienung Stammdaten Kennwort ändern Navigation: Bedienung Stammdaten Kennwort ändern Möchten Sie Ihr Kennwort ändern? Geben Sie dazu Ihr bisherig...",""],
["codes.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Codes","Bedienung PEPP-Vorschlagsverfahren Codes Navigation: Bedienung PEPP-Vorschlagsverfahren Codes Bei einem Vorschlag zur Weiterentwicklung Leistungsb...",""],
["documents.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Dokumente","Bedienung PEPP-Vorschlagsverfahren Dokumente Navigation: Bedienung PEPP-Vorschlagsverfahren Dokumente In dieser Registerkarte haben Sie die Möglic...",""],
["dropbox.htm","Bedienung &#62; DropBox","Bedienung DropBox Navigation: Bedienung DropBox Haben Sie größere Datenmengen, die Sie im Rahmen der Datenlieferung gem. 21 KHEntgG oder aus sonst...",""],
["dropboxcreate.htm","Bedienung &#62; DropBox &#62; DropBox anlegen","Bedienung DropBox DropBox anlegen Navigation: Bedienung DropBox DropBox anlegen Nach Klick auf [DropBox anlegen] erhalten Sie diesen Dialog: Abb. ...",""],
["dropboxfill.htm","Bedienung &#62; DropBox &#62; DropBox befüllen","Bedienung DropBox DropBox befüllen Navigation: Bedienung DropBox DropBox befüllen Wählen Sie aus der Liste der offenen DropBoxen (siehe oben) die ...",""],
["editusermaintenance.htm","Bedienung &#62; Stammdaten &#62; Stammdaten editieren","Bedienung Stammdaten Stammdaten editieren Navigation: Bedienung Stammdaten Stammdaten editieren Die Stammdaten entsprechen im Wesentlichen den Dat...",""],
["features.htm","Bedienung &#62; Stammdaten &#62; Funktionen","Bedienung Stammdaten Funktionen Navigation: Bedienung Stammdaten Funktionen Das InEK Datenportal ist dafür ausgelegt, Ihnen künftig eine Vielzahl ...",""],
["introduction.htm","Einführung","Einführung Navigation: No topics above this level Einführung Das InEK Datenportal wurde entwickelt, um Ihnen auf komfortable Art und Weise die Ein...",""],
["login.htm","Bedienung &#62; Login","Bedienung Login Navigation: Bedienung Login Startpunkt des InEK Datenportal ist der Login-Dialog. Die zu übermittelnden Daten dienen insbesondere ...",""],
["notes.htm","Einführung &#62; Hinweise","Einführung Hinweise Navigation: Einführung Hinweise Dieses Handbuch enthält diverse Abbildungen des Programms (Screenshots). Das Aussehen der Dial...",""],
["overview.htm","Bedienung &#62; Übersicht","Bedienung Übersicht Navigation: Bedienung Übersicht Die Übersicht ist die \"Schaltzentrale\" Ihres Portals. Hier werden die von Ihnen gewählten Funk...",""],
["pepp-propblem.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Problemstellung, Lösungsvorschlag","Bedienung PEPP-Vorschlagsverfahren Problemstellung, Lösungsvorschlag Navigation: Bedienung PEPP-Vorschlagsverfahren Problemstellung, Lösungsvorsch...",""],
["peppproposal.htm","Bedienung &#62; PEPP-Vorschlagsverfahren","Bedienung PEPP-Vorschlagsverfahren Navigation: Bedienung PEPP-Vorschlagsverfahren Das PEPP-Vorschlagsverfahren dient dazu, externen Sachverstand i...",""],
["preconditions.htm","Einführung &#62; Systemvoraussetzung","Einführung Systemvoraussetzung Navigation: Einführung Systemvoraussetzung Beim InEK Datenportal handelt es sich um eine Applikation, die auf einem...",""],
["register.htm","Bedienung &#62; Registrierung","Bedienung Registrierung Navigation: Bedienung Registrierung Um den Service nutzen zu können, ist eine vorherige Registrierung erforderlich. Klicke...",""],
["requestpassword.htm","Bedienung &#62; Kennwort anfordern","Bedienung Kennwort anfordern Navigation: Bedienung Kennwort anfordern Sollten Sie als registrierter Anwender einmal Ihr Kennwort vergessen haben, ...",""],
["search.htm","Bedienung &#62; Suche","Bedienung Suche Navigation: Bedienung Suche In diversen Formularen, z.B. beim PEPP-Vorschlagsverfahren, wird die Eingabe von Codes benötigt. Das I...",""],
["termsofuse.htm","Einführung &#62; Nutzungsbedingungen","Einführung Nutzungsbedingungen Navigation: Einführung Nutzungsbedingungen Das InEK stellt das InEK Datenportal für interessierte Nutzer kostenlos ...",""],
["testedbrowsers.htm","Anhang &#62; Getestete Browser","Anhang Getestete Browser Navigation: Anhang Getestete Browser Das InEK Datenportal wurde und wird vom InEK mit diversen Browsern auf den InEK-Syst...",""],
["usage.htm","Bedienung","Bedienung Navigation: No topics above this level Bedienung Die Bedienung des InEK Datenportals wurde so gestaltet, dass sie weitgehend intuitiv od...",""],
["userinformation.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Stammformblatt","Bedienung PEPP-Vorschlagsverfahren Damit das InEK Sie über den Status Ihres Vorschlags informieren kann, ist die Angabe Ihrer Adresse erforderlich...",""],
["usermaintenance.htm","Bedienung &#62; Stammdaten","Bedienung Stammdaten Navigation: Bedienung Stammdaten Die Stammdaten dienen der Speicherung von Informationen zu Ihrem Benutzerkonto und Ihrem Kra...",""],
["usermaintenanceother.htm","Bedienung &#62; Stammdaten &#62; Sonstiges","Bedienung Stammdaten Sonstiges Navigation: Bedienung Stammdaten Sonstiges Im Bereich Sonstiges steht Ihnen eine Funktion zum Löschen Ihres Portal-...",""],
["webrequest_ftsearch.htm","InEK Datenportal","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""]];
