pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["additionaliks.htm","Bedienung &#62; Stammdaten &#62; Weitere IKs","Weitere IKs",""],
["aenderungshistorie.htm","Anhang &#62; Änderungshistorie","Änderungshistorie",""],
["basehandling.htm","Bedienung &#62; Allgemeine Bedienung","Allgemeine Bedienung",""],
["changepassword.htm","Bedienung &#62; Stammdaten &#62; Kennwort ändern","Bedienung Stammdaten Kennwort ändern Navigation: Bedienung Stammdaten Kennwort ändern Möchten Sie Ihr Kennwort ändern? Geben Sie dazu Ihr bisherig...",""],
["codes.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Kodes","Kodes",""],
["cooperation.htm","Bedienung &#62; Kooperation","Kooperation",""],
["cooperationconfigure.htm","Bedienung &#62; Kooperation &#62; Kooperation konfigurieren","Kooperation konfigurieren",""],
["cooperationstart.htm","Bedienung &#62; Kooperation &#62; Kooperation starten","Kooperation starten",""],
["datavisibility.htm","Bedienung &#62; Sichtbarkeit der Daten","Sichtbarkeit der Daten",""],
["documents.htm","Bedienung &#62; Dokumente","Dokumente",""],
["dropbox.htm","Bedienung &#62; DropBox","DropBox",""],
["dropboxcreate.htm","Bedienung &#62; DropBox &#62; DropBox anlegen","DropBox anlegen",""],
["dropboxfill.htm","Bedienung &#62; DropBox &#62; DropBox befüllen","DropBox befüllen",""],
["editusermaintenance.htm","Bedienung &#62; Stammdaten &#62; Stammdaten editieren","Stammdaten editieren",""],
["enhancement.htm","Einführung &#62; Weiterentwicklung / Anfragen","Weiterentwicklung / Anfragen",""],
["features.htm","Funktionen","Funktionen",""],
["help.htm","Bedienung &#62; Hilfe","Hilfe",""],
["iksupervisor.htm","Bedienung &#62; IK-Supervisor","IK-Supervisor",""],
["introduction.htm","Einführung","Einführung",""],
["konfiguration.htm","Bedienung &#62; Stammdaten &#62; Konfiguration","Konfiguration",""],
["login.htm","Bedienung &#62; Login","Login",""],
["maintenancefeatures.htm","Bedienung &#62; Stammdaten &#62; Funktionen","Funktionen",""],
["notes.htm","Einführung &#62; Hinweise","Hinweise",""],
["nub.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB)","Neue Untersuchungs- und Behandlungsmethoden (NUB)",""],
["nubaddcosts.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Mehrkosten","Mehrkosten",""],
["nubdescription.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Beschreibung","Beschreibung",""],
["nubdetails.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Methodendetails","Methodendetails",""],
["nubkeyfigures.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Kennzahlen","Kennzahlen",""],
["nublist.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Auflistung NUB-Anfragen","Auflistung NUB-Anfragen",""],
["nubuserinformation.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Stammformblatt","Stammformblatt",""],
["overview.htm","Bedienung &#62; Übersicht","Übersicht",""],
["overviewfeatures.htm","Einführung &#62; Funktionsüberblick","Funktionsüberblick",""],
["pepp-propblem.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Problemstellung, Lösungsvorschlag","Problemstellung, Lösungsvorschlag",""],
["peppdocuments.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Dokumente","Dokumente",""],
["peppproposal.htm","Bedienung &#62; PEPP-Vorschlagsverfahren","PEPP-Vorschlagsverfahren",""],
["preconditions.htm","Einführung &#62; Systemvoraussetzung","Systemvoraussetzung",""],
["register.htm","Bedienung &#62; Registrierung","Registrierung",""],
["requestpassword.htm","Bedienung &#62; Kennwort anfordern","Kennwort anfordern",""],
["search.htm","Bedienung &#62; Suche","Suche",""],
["templates.htm","Bedienung &#62; Neue Untersuchungs- und Behandlungsmethoden (NUB) &#62; Vorlagen","Vorlagen",""],
["termsofuse.htm","Einführung &#62; Nutzungsbedingungen","Nutzungsbedingungen",""],
["testedbrowsers.htm","Anhang &#62; Getestete Browser","Getestete Browser",""],
["usage.htm","Bedienung","Bedienung",""],
["userinformation.htm","Bedienung &#62; PEPP-Vorschlagsverfahren &#62; Stammformblatt","Stammformblatt",""],
["usermaintenance.htm","Bedienung &#62; Stammdaten","Stammdaten",""],
["usermaintenanceother.htm","Bedienung &#62; Stammdaten &#62; Sonstiges","Sonstiges",""],
["webrequest_content.htm","InEK Datenportal","Einführung Nutzungsbedingungen Systemvoraussetzung Hinweise Bedienung Allgemeine Bedienung Login Registrierung Kennwort anfordern Übersicht Suche ...",""],
["webrequest_ftsearch.htm","InEK Datenportal","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""],
["webrequest_kwindex.htm","InEK Datenportal","- B - Bedienung Betriebssystem - D - Datenlieferung Datenportal Dialogbedienung Dokumente DropBox - E - Einführung - G - Gewährleistung - H - Haft...",""]];
